name: uaa_map
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^1.0.3
  flutter_typeahead: ^4.0.0
  http: ^0.13.4
  sqflite: ^2.3.0
  path: ^1.8.3
  connectivity_plus: ^5.0.2
  flutter_markdown: ^0.6.10
  animated_text_kit: ^4.2.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/buildings/1.svg
    - assets/images/buildings/1a.svg
    - assets/images/buildings/1b.svg
    - assets/images/buildings/2.svg
    - assets/images/buildings/3.svg
    - assets/images/buildings/4.svg
    - assets/images/buildings/5.svg
    - assets/images/buildings/6.svg
    - assets/images/buildings/6a.svg
    - assets/images/buildings/7.svg
    - assets/images/buildings/8.svg
    - assets/images/buildings/8a.svg
    - assets/images/buildings/9.svg
    - assets/images/buildings/10.svg
    - assets/images/buildings/11.svg
    - assets/images/buildings/12.svg
    - assets/images/buildings/13.svg
    - assets/images/buildings/13b.svg
    - assets/images/buildings/14.svg
    - assets/images/buildings/15.svg
    - assets/images/buildings/16.svg
    - assets/images/buildings/17.svg
    - assets/images/buildings/18.svg
    - assets/images/buildings/19.svg
    - assets/images/buildings/20.svg
    - assets/images/buildings/21.svg
    - assets/images/buildings/22.svg
    - assets/images/buildings/23.svg
    - assets/images/buildings/24.svg
    - assets/images/buildings/25.svg
    - assets/images/buildings/26.svg
    - assets/images/buildings/27.svg
    - assets/images/buildings/28.svg
    - assets/images/buildings/29.svg
    - assets/images/buildings/30.svg
    - assets/images/buildings/31.svg
    - assets/images/buildings/32.svg
    - assets/images/buildings/33.svg
    - assets/images/buildings/34.svg
    - assets/images/buildings/35.svg
    - assets/images/buildings/36.svg
    - assets/images/buildings/37.svg
    - assets/images/buildings/38.svg
    - assets/images/buildings/39.svg
    - assets/images/buildings/40.svg
    - assets/images/buildings/41.svg
    - assets/images/buildings/42.svg
    - assets/images/buildings/43.svg
    - assets/images/buildings/44.svg
    - assets/images/buildings/45.svg
    - assets/images/buildings/46.svg
    - assets/images/buildings/47.svg
    - assets/images/buildings/48.svg
    - assets/images/buildings/49.svg
    - assets/images/buildings/50.svg
    - assets/images/buildings/51.svg
    - assets/images/buildings/52.svg
    - assets/images/buildings/53.svg
    - assets/images/buildings/54.svg
    - assets/images/buildings/55.svg
    - assets/images/buildings/56.svg
    - assets/images/buildings/57.svg
    - assets/images/buildings/58.svg
    - assets/images/buildings/59.svg
    - assets/images/buildings/60.svg
    - assets/images/buildings/61.svg
    - assets/images/buildings/62.svg
    - assets/images/buildings/63.svg
    - assets/images/buildings/64.svg
    - assets/images/buildings/65.svg
    - assets/images/buildings/66.svg
    - assets/images/buildings/201.svg
    - assets/images/buildings/202.svg
    - assets/images/buildings/203.svg
    - assets/images/buildings/204.svg
    - assets/images/buildings/205.svg
    - assets/images/buildings/206.svg
    - assets/images/buildings/207.svg
    - assets/images/buildings/208.svg
    - assets/images/buildings/210.svg
    - assets/images/buildings/211.svg
    - assets/images/buildings/212.svg
    - assets/images/buildings/213.svg
    - assets/images/buildings/214.svg
    - assets/images/buildings/215.svg
    - assets/images/buildings/219.svg
    - assets/images/buildings/220.svg
    - assets/images/buildings/221.svg
    - assets/images/buildings/222.svg
    - assets/images/buildings/223.svg
    - assets/images/buildings/224.svg
    - assets/images/buildings/alberca.svg
    - assets/images/background/background_v3.svg
    - assets/images/logos/logo_uaa.png
    - assets/images/signs/bathroom.svg
    - assets/images/signs/cafeteria.svg
    - assets/images/signs/estacionamiento.svg
